language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "nightly"
# command to install dependencies
install:
  - "pip install flake8 pytest ."
# command to run tests
script:
  - "py.test tests/"
  - "cd snippets && AHEUI=../rpaheui.py ./test.sh --disable logo"
sudo: false
