language: python
python:
  - "pypy2.7-5.10.0"
  - "pypy3.5-5.10.1"
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install flake8 pytest ."
# command to run tests
script:
  - "py.test tests/"
  - "cd snippets && AHEUI=../rpaheui.py ./test.sh --disable logo"
sudo: false
